### PR TITLE
Dev k8s runner its

### PR DESCRIPTION
**Pull request by almahmoud**

### CODE REVIEW

**Comment by almahmoud** [comment]
/deploy extraargs="--set image.pullPolicy=Always --set image.tag=21.05"

**Comment by galaxy-k8s** [comment]
Preview command dispatched, starting deployment on default cluster

**Comment by almahmoud** [comment]
/deploy extraargs="--set image.pullPolicy=Always --set image.tag=21.05"

**Comment by galaxy-k8s** [comment]
Preview command dispatched, starting deployment on default cluster

**Comment by almahmoud** [comment]
/deploy extraargs="--set image.pullPolicy=Always --set image.tag=21.05 --set image.repository=galaxy/galaxy-min"

**Comment by galaxy-k8s** [comment]
Preview command dispatched, starting deployment on default cluster

**Comment by galaxy-k8s** [comment]
Release "pr-9-gxy-rls" has been upgraded. Happy Helming!
NAME: pr-9-gxy-rls
LAST DEPLOYED: Tue Jun 22 02:52:06 2021
NAMESPACE: pr-9
STATUS: deployed
REVISION: 2
NOTES:
1. Get the application URL by running these commands:
 https://kubedev.usegalaxy.org/galaxy-pr-9

**Comment by galaxy-k8s** [comment]
See your startup logs for 'galaxy-pr-9-22-06-21 02:55:10' at: https://gist.githubusercontent.com/galaxy-k8s/7438e4065584c10ba546bb03fa3f12e5

**Comment by galaxy-k8s** [comment]
Preview command dispatched, starting deployment on default cluster

**Comment by almahmoud** [comment]
/deploy extraargs="--set image.pullPolicy=Always --set image.tag=21.05"

**Comment by galaxy-k8s** [comment]
Preview command dispatched, starting deployment on default cluster

**Comment by galaxy-k8s** [comment]
release "pr-9-gxy-rls" uninstalled

**Pull request closed without merging**
